# Generated by Django 3.1.5 on 2021-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('type', models.CharField(choices=[('H2', 'Title'), ('H3', 'Title2'), ('TXT', 'Text'), ('IMG', 'Image'), ('YT', 'YoutubeEmbed'), ('LINK', 'Link')], default='H2', max_length=5, verbose_name='About section type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=50, verbose_name='Description of section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.about',),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.about',),
        ),
        migrations.CreateModel(
            name='AboutTitle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.about',),
        ),
        migrations.CreateModel(
            name='AboutTitle2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.about',),
        ),
        migrations.CreateModel(
            name='AboutYoutubeEmbed',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.about',),
        ),
    ]
