# Generated by Django 3.1.5 on 2021-02-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "Preview"},
        ),
    ]
