# Generated by Django 3.1.5 on 2021-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210212_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Preview', 'verbose_name_plural': 'Previews'},
        ),
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'Vsebina', 'verbose_name_plural': 'Vsebine'},
        ),
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': 'Slika', 'verbose_name_plural': 'Slike'},
        ),
        migrations.AlterModelOptions(
            name='abouttitle',
            options={'verbose_name': 'Naslov', 'verbose_name_plural': 'Naslovi'},
        ),
        migrations.AlterModelOptions(
            name='abouttitle2',
            options={'verbose_name': 'Naslov 2', 'verbose_name_plural': 'Naslovi 2'},
        ),
        migrations.AlterModelOptions(
            name='aboutyoutubeembed',
            options={'verbose_name': 'Youtube embed', 'verbose_name_plural': 'Youtube embedi'},
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='about',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Razvrsti'),
        ),
        migrations.AlterField(
            model_name='about',
            name='type',
            field=models.CharField(choices=[('H2', 'Title'), ('H3', 'Title2'), ('TXT', 'Besedilo'), ('IMG', 'Slika'), ('YT', 'YoutubeEmbed'), ('LINK', 'Link')], default='H2', max_length=5, verbose_name='About section type'),
        ),
    ]
