# Generated by Django 3.1.5 on 2021-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_auto_20210401_1838"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "Predogled", "verbose_name_plural": "Predogled"},
        ),
        migrations.AlterModelOptions(
            name="aboutyoutubeembed",
            options={
                "verbose_name": "Youtube Embed",
                "verbose_name_plural": "Youtube Embed",
            },
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Vsebina"),
        ),
        migrations.AlterField(
            model_name="about",
            name="description",
            field=models.CharField(max_length=50, verbose_name="Opis sekcije"),
        ),
        migrations.AlterField(
            model_name="about",
            name="order",
            field=models.IntegerField(default=1, verbose_name="Vstni red"),
        ),
        migrations.AlterField(
            model_name="about",
            name="type",
            field=models.CharField(
                choices=[
                    ("H2", "Title"),
                    ("H3", "Naslov 2"),
                    ("TXT", "Besedilo"),
                    ("IMG", "Slika"),
                    ("YT", "Youtube Embed"),
                    ("LINK", "Povezava"),
                ],
                default="H2",
                max_length=5,
                verbose_name="About section type",
            ),
        ),
    ]
