# Generated by Django 3.1.5 on 2021-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210602_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ustvarjeno'),
        ),
        migrations.AlterField(
            model_name='about',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Modified'),
        ),
    ]
