apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: izboljsajmo-maribor-backend-pv-claim
  labels:
    app: izboljsajmo-maribor-backend
spec:
  storageClassName: 'scw-bssd-retain'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: izboljsajmo-maribor-backend
  labels:
    app: izboljsajmo-maribor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izboljsajmo-maribor-backend
  template:
    metadata:
      labels:
        app: izboljsajmo-maribor-backend
    spec:
      volumes:
      - name: izboljsajmo-maribor-backend-persistent-storage
        persistentVolumeClaim:
          claimName: izboljsajmo-maribor-backend-pv-claim
      containers:
      - name: izboljsajmo-maribor-backend
        image: backend # kustomize thing
        volumeMounts:
        - name: izboljsajmo-maribor-backend-persistent-storage
          mountPath: /files
        command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000'] # TODO
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /v1/
            port: http
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        env:
          - name: APP_ENV
            value: production
          - name: SECRET_DB_NAME
            value: mb-initiative
          - name: SECRET_DB_USERNAME
            value: postgres
          - name: SECRET_DB_PASSWORD
            value: initititit!
          - name: STATIC_URL_BASE
            value: https://files.izboljsajmo-maribor.k8s.djnd.si
          - name: MEDIA_URL_BASE
            value: https://files.izboljsajmo-maribor.k8s.djnd.si
      - name: izboljsajmo-maribor-nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        image: nginx:alpine
        volumeMounts:
        - name: izboljsajmo-maribor-backend-persistent-storage
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: izboljsajmo-maribor-backend
spec:
  selector:
    app: izboljsajmo-maribor-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: izboljsajmo-maribor-nginx
spec:
  selector:
    app: izboljsajmo-maribor-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izboljsajmo-maribor-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - api.izboljsajmo-maribor.k8s.djnd.si
    secretName: izboljsajmo-maribor-backend-tls
  rules:
  - host: api.izboljsajmo-maribor.k8s.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: izboljsajmo-maribor-backend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izboljsajmo-maribor-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - files.izboljsajmo-maribor.k8s.djnd.si
    secretName: izboljsajmo-maribor-backend-tls
  rules:
  - host: files.izboljsajmo-maribor.k8s.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: izboljsajmo-maribor-nginx
            port:
              number: 80
