
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izboljsajmo-maribor
resources:
  - backend.yaml
  - frontend.yaml
  - postgis.yaml
images:
- name: frontend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-frontend
  newTag: 'a807190cfc948032c1abc8ddb4129ba2bf6a2f8e'
- name: backend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
  newTag: 'a807190cfc948032c1abc8ddb4129ba2bf6a2f8e'
