
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izboljsajmo-maribor
resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - frontend.yaml
  - postgis.yaml
images:
- name: frontend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-frontend
  newTag: 'e811bde5fcba476428dd255c0947918a7ac05ea3'
- name: backend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
  newTag: 'e811bde5fcba476428dd255c0947918a7ac05ea3'
