
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izboljsajmo-maribor
resources:
  - backend.yaml
  - frontend.yaml
  - postgis.yaml
images:
- name: frontend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-frontend
  newTag: '16b9c64059e11f1dc86a5e7331c4599669905862'
- name: backend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
  newTag: '16b9c64059e11f1dc86a5e7331c4599669905862'
