
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izboljsajmo-maribor
resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - frontend.yaml
  - postgis.yaml
images:
- name: frontend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-frontend
  newTag: 'd5eb7ff9d52b82759c625b1716029ba3d748f2bc'
- name: backend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
  newTag: 'd5eb7ff9d52b82759c625b1716029ba3d748f2bc'
