
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izboljsajmo-maribor
resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - frontend.yaml
  - postgis.yaml
images:
- name: frontend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-frontend
  newTag: 'ad1c162013ebdf613513ef888b0643419717674c'
- name: backend
  newName: rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
  newTag: 'ad1c162013ebdf613513ef888b0643419717674c'
