
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis-im
  labels:
    app: postgis-im
spec:
  serviceName: postgres-sfc
  replicas: 1
  selector:
    matchLabels:
      app: postgis-im
  template:
    metadata:
      labels:
        app: postgis-im
    spec:
      containers:
      - name: postgis-im
        image: postgis/postgis
        resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "300Mi"
              cpu: "250m"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: izboljsajmo-maribor-credentials
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgisdb
              subPath: postgres
      volumes:
        - name: postgisdb
          persistentVolumeClaim:
            claimName: postgis-volumeclaim

  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: postgisdb
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: scw-bssd-retain
        resources:
          requests:
            storage: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: postgis-im
spec:
  selector:
    app: postgis-im
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
