version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - '6379:6379'

  postgis:
    image: mdillon/postgis
    ports:
      - "5430:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_DB=mb-initiative
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=initititit!


  mb-api:
    build: backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./backend:/app
        - ./backend/static:/static
        - .backend/media:/media
    ports:
        - "8000:8000"
    depends_on:
        - postgis

  celery:
    build: backend/.
    command: celery -A mb_initiative worker -l INFO
    volumes:
        - .:/usr/src/app

volumes:
  db-data:

