version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - '6379:6379'

  postgis:
    image: postgis/postgis
    ports:
      - "5430:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_DB=mbinitiative
      - POSTGRES_USER=maribor
      - POSTGRES_PASSWORD=maribor

  mb-api:
    build: backend/.
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
        - ./backend:/app
        - ./backend/static:/static
        - .backend/media:/media
    ports:
        - "8080:8080"
    depends_on:
        - postgis

  celery:
    build: backend/.
    command: celery -A mb_initiative worker -l DEBUG -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
        - .:/usr/src/app

volumes:
  db-data:

