# Generated by Django 3.1.5 on 2021-02-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('MM', 'MOTI ME!'), ('II', 'IMAM IDEJO!'), ('ZM', 'ZANIMA ME!')], default='MM', max_length=2, verbose_name='Initiative type')),
                ('order', models.IntegerField(default=0)),
                ('field', models.CharField(max_length=50, verbose_name='Field name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives_descriptiondefinition_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
