# Generated by Django 3.1.5 on 2021-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BothersInitiative',
        ),
        migrations.CreateModel(
            name='BothersInitiativeArea',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='BothersInitiativeContractor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='BothersInitiativeSuper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.AddField(
            model_name='initiative',
            name='reviwer',
            field=models.CharField(choices=[('SA', 'SUPER ADMIN'), ('AA', 'AREA ADMIN'), ('AP', 'AREA APPRAISER'), ('CA', 'CONTRACTOR APPRAISER')], default='SA', max_length=2, verbose_name='Reviwer'),
        ),
    ]
