# Generated by Django 3.1.5 on 2021-03-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_auto_20210301_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinitiative',
            name='publication_status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='Publication Status'),
        ),
    ]
