# Generated by Django 3.1.5 on 2021-02-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_auto_20210203_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinitiative',
            name='competent_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_statuses', to='initiatives.competentservice', verbose_name='CompetentService'),
        ),
    ]
