# Generated by Django 3.1.5 on 2021-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_statusinitiative_competent_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='in_review',
            field=models.BooleanField(default=False, verbose_name='In review'),
        ),
    ]
