# Generated by Django 3.1.5 on 2021-03-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0004_auto_20210311_1327"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BothersInitiativeContractor",
        ),
        migrations.CreateModel(
            name="BothersInitiativeAppraiser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("initiatives.initiative",),
        ),
    ]
