# Generated by Django 3.1.5 on 2021-02-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_auto_20210204_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
