# Generated by Django 3.1.5 on 2021-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_remove_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='address',
            field=models.CharField(default='dummy', max_length=10, verbose_name='Address of initiative'),
            preserve_default=False,
        ),
    ]
