# Generated by Django 3.1.5 on 2021-03-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_auto_20210315_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdeaInitiative',
        ),
        migrations.DeleteModel(
            name='InterestedInitiative',
        ),
        migrations.CreateModel(
            name='BothersInitiativeContractor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='IdeaInitiativeAppraiser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='IdeaInitiativeArea',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='IdeaInitiativeContractor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='IdeaInitiativeSuper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='InterestedInitiativeAppraiser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='InterestedInitiativeArea',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
        migrations.CreateModel(
            name='InterestedInitiativeSuper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.initiative',),
        ),
    ]
