# Generated by Django 3.1.5 on 2021-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address of initiative'),
        ),
    ]
