# Generated by Django 3.1.5 on 2021-02-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_auto_20210205_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='initiatives.initiative', verbose_name='Initiative'),
        ),
    ]
