# Generated by Django 3.1.5 on 2021-03-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_auto_20210317_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.user',),
        ),
    ]
