# Generated by Django 3.1.5 on 2021-02-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_auto_20210209_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Description title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_comments', to='initiatives.initiative', verbose_name='Initiative'),
        ),
    ]
