# Generated by Django 3.1.5 on 2021-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0010_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(default='tmp', max_length=50, verbose_name='Description of section'),
            preserve_default=False,
        ),
    ]
