# Generated by Django 3.1.5 on 2021-03-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_auto_20210322_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='initiatives.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='initiatives.zone', verbose_name='GEO Zone of initiative'),
        ),
    ]
