# Generated by Django 3.1.5 on 2021-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='about',
            name='type',
            field=models.CharField(choices=[('H2', 'Title'), ('H3', 'Title2'), ('TXT', 'Text'), ('IMG', 'Image'), ('YT', 'YoutubeEmbed'), ('LINK', 'Link')], default='H2', max_length=5, verbose_name='About section type'),
        ),
    ]
