# Generated by Django 3.1.5 on 2021-02-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_auto_20210212_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
