# Generated by Django 3.1.5 on 2021-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0013_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInitiativeDone',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.CreateModel(
            name='StatusInitiativeEditing',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.CreateModel(
            name='StatusInitiativeFinished',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.CreateModel(
            name='StatusInitiativeHear',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.CreateModel(
            name='StatusInitiativeProgress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.CreateModel(
            name='StatusInitiativeRejected',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.statusinitiative',),
        ),
        migrations.AddField(
            model_name='statusinitiative',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='Is email sent'),
        ),
    ]
