# Generated by Django 3.1.5 on 2021-02-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_auto_20210216_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_before', to='initiatives.image', verbose_name='Cover image before'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='cover_image_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_after', to='initiatives.image', verbose_name='Cover image after'),
        ),
    ]
