# Generated by Django 3.1.5 on 2021-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0015_auto_20210329_0757"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("initiatives.user",),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SA", "SUPER ADMIN"),
                    ("AA", "AREA ADMIN"),
                    ("AP", "AREA APPRAISER"),
                    ("CA", "CONTRACTOR APPRAISER"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
