# Generated by Django 3.1.5 on 2021-02-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0016_auto_20210216_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='in_review',
            new_name='is_draft',
        ),
    ]
