# Generated by Django 3.1.5 on 2021-03-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0017_auto_20210329_2154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="competent_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="initiatives.competentservice",
                verbose_name="Competent service",
            ),
        ),
    ]
