# Generated by Django 3.1.5 on 2021-04-01 18:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import initiatives.utils


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0018_auto_20210330_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedinitiative',
            options={'verbose_name': 'Arhivirana pobuda', 'verbose_name_plural': 'Arhivirane pobude'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Področje', 'verbose_name_plural': 'Področja'},
        ),
        migrations.AlterModelOptions(
            name='areaadminuser',
            options={'verbose_name': 'Admin področni', 'verbose_name_plural': 'Admini področni'},
        ),
        migrations.AlterModelOptions(
            name='areaappraiseruser',
            options={'verbose_name': 'Cenilec področni', 'verbose_name_plural': 'Cenilci področni'},
        ),
        migrations.AlterModelOptions(
            name='basicuser',
            options={'verbose_name': 'Basic user', 'verbose_name_plural': 'Basic users'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativeappraiser',
            options={'verbose_name': 'Pobuda moti me (cenilec področni)', 'verbose_name_plural': 'Pobude moti me (cenilci področni)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativearea',
            options={'verbose_name': 'Pobuda moti me (admin področni)', 'verbose_name_plural': 'Pobude moti me (admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativecontractor',
            options={'verbose_name': 'Pobuda moti me (cenilec izvajalec)', 'verbose_name_plural': 'Pobude moti me (cenilci izvajalci)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativesuper',
            options={'verbose_name': 'Pobuda moti me (superadmin)', 'verbose_name_plural': 'Pobude moti me (superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentarji'},
        ),
        migrations.AlterModelOptions(
            name='confirmemail',
            options={'verbose_name': 'Confirm email', 'verbose_name_plural': 'Confirm emails'},
        ),
        migrations.AlterModelOptions(
            name='contractorappraiseruser',
            options={'verbose_name': 'Cenilec izvajalec', 'verbose_name_plural': 'Cenilci izvajalec'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Opis', 'verbose_name_plural': 'Opisi'},
        ),
        migrations.AlterModelOptions(
            name='descriptiondefinition',
            options={'verbose_name': 'Razdelek opisa', 'verbose_name_plural': 'Razdeleki opisa'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Datoteka', 'verbose_name_plural': 'Datoteke'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativeappraiser',
            options={'verbose_name': 'Pobuda imam idejo (cenilec področni)', 'verbose_name_plural': 'Pobude imam idejo (cenilec področni)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativearea',
            options={'verbose_name': 'Pobuda imam idejo (admin področni)', 'verbose_name_plural': 'Pobude imam idejo (admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativecontractor',
            options={'verbose_name': 'Pobuda imam idejo (cenilec izvajalec)', 'verbose_name_plural': 'Pobude imam idejo (cenilec izvajalec)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativesuper',
            options={'verbose_name': 'Pobuda imam idejo (superadmin)', 'verbose_name_plural': 'Pobude imam idejo (superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Slika', 'verbose_name_plural': 'Slike'},
        ),
        migrations.AlterModelOptions(
            name='initiative',
            options={'verbose_name': 'Pobuda', 'verbose_name_plural': 'Pobude'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativeappraiser',
            options={'verbose_name': 'Pobuda zanima me (cenilec področni)', 'verbose_name_plural': 'Pobude zanima me (cenilec področni)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativearea',
            options={'verbose_name': 'Pobuda zanima me (admin področni)', 'verbose_name_plural': 'Pobude zanima me (admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativesuper',
            options={'verbose_name': 'Pobuda zanima me (superadmin)', 'verbose_name_plural': 'Pobude zanima me (superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizacija', 'verbose_name_plural': 'Organizacije'},
        ),
        migrations.AlterModelOptions(
            name='rejection',
            options={'verbose_name': 'Zavrnitev', 'verbose_name_plural': 'Zavrnitve'},
        ),
        migrations.AlterModelOptions(
            name='restorepassword',
            options={'verbose_name': 'Restore password', 'verbose_name_plural': 'Restore passwords'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statusi'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiative',
            options={'verbose_name': 'Status pobude', 'verbose_name_plural': 'Statusi pobude'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativedone',
            options={'verbose_name': 'Status pobude izvedeno', 'verbose_name_plural': 'Statusi pobude izvedeno'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativeediting',
            options={'verbose_name': 'Status pobude urejamo', 'verbose_name_plural': 'Statusi pobude urejamo'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativefinished',
            options={'verbose_name': 'Status pobude zaključeno', 'verbose_name_plural': 'Statusi pobude zaključeno'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativehear',
            options={'verbose_name': 'Status pobude slišimo', 'verbose_name_plural': 'Statusi pobude slišimo'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativeprogress',
            options={'verbose_name': 'Status pobude v izvajanju', 'verbose_name_plural': 'Statusi pobude v izvajanju'},
        ),
        migrations.AlterModelOptions(
            name='statusinitiativerejected',
            options={'verbose_name': 'Status pobude zavrnjeno', 'verbose_name_plural': 'Statusi pobude zavrnjeno'},
        ),
        migrations.AlterModelOptions(
            name='superadminuser',
            options={'verbose_name': 'Super admin', 'verbose_name_plural': 'Super admin'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uporabnik', 'verbose_name_plural': 'Uporabniki'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Glas', 'verbose_name_plural': 'Glasovi'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Območje', 'verbose_name_plural': 'Območja'},
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmemail',
            name='key',
            field=models.CharField(max_length=50, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='confirmemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conform_emails', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Razvrsti'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files', validators=[initiatives.utils.validate_file_extension], verbose_name='Datoteka'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ime'),
        ),
        migrations.AlterField(
            model_name='restorepassword',
            name='key',
            field=models.CharField(max_length=50, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='restorepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_passwords', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+ -]+$', 'Enter a valid username.', 'invalid')], verbose_name='uporabniško ime'),
        ),
    ]
