# Generated by Django 3.1.5 on 2021-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0019_auto_20210401_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
