# Generated by Django 3.1.5 on 2021-04-07 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0020_user_blocked_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('nw', 'NEW'), ('up', 'UPDATED')], default='nw', max_length=2, verbose_name='Notification type')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is sent')),
                ('for_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='initiatives.area', verbose_name='Area')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='initiatives.initiative', verbose_name='Initiative')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created', 'is_sent'], name='initiatives_created_fdf2b7_idx'),
        ),
    ]
