# Generated by Django 3.1.5 on 2021-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0022_auto_20210407_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                verbose_name="elektronski naslov",
            ),
        ),
    ]
