# Generated by Django 3.1.5 on 2021-06-02 12:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0026_auto_20210415_1411"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basicuser",
            options={
                "verbose_name": "Naveden uporabnik",
                "verbose_name_plural": "Navadni uporabniki",
            },
        ),
        migrations.AlterModelOptions(
            name="confirmemail",
            options={
                "verbose_name": "Potrditev registracije na platformi Izboljšajmo Maribor",
                "verbose_name_plural": "Potrdi email naslov",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Organizacija",
                "verbose_name_plural": "Organizacija",
            },
        ),
        migrations.AlterModelOptions(
            name="restorepassword",
            options={
                "verbose_name": "Ponastavitev gesla za dostop do platforme Izboljšajmo Maribor",
                "verbose_name_plural": "Ponastavi geslo",
            },
        ),
        migrations.AlterModelOptions(
            name="statusinitiative",
            options={
                "verbose_name": "Status pobude",
                "verbose_name_plural": "Statusi pobud",
            },
        ),
        migrations.AlterModelOptions(
            name="superadminuser",
            options={"verbose_name": "Superadmin", "verbose_name_plural": "Superadmin"},
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={
                "verbose_name": "Mestna četrt/Krajevna skupnost",
                "verbose_name_plural": "Območja",
            },
        ),
        migrations.AlterField(
            model_name="area",
            name="competent_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="initiatives.competentservice",
                verbose_name="Pristojna služba",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Ime območja"),
        ),
        migrations.AlterField(
            model_name="area",
            name="note",
            field=models.TextField(verbose_name="Opisi"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Komentar"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="initiative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiative_comments",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("PU", "PUBLISHED"), ("D", "DELETED"), ("PE", "PENDING")],
                default="PU",
                max_length=2,
                verbose_name="Status komentarja",
            ),
        ),
        migrations.AlterField(
            model_name="competentservice",
            name="description",
            field=models.TextField(verbose_name="Opis storitve"),
        ),
        migrations.AlterField(
            model_name="competentservice",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Ime območja"),
        ),
        migrations.AlterField(
            model_name="confirmemail",
            name="key",
            field=models.CharField(max_length=50, verbose_name="ključ"),
        ),
        migrations.AlterField(
            model_name="description",
            name="content",
            field=models.TextField(verbose_name="Vsebina opisa"),
        ),
        migrations.AlterField(
            model_name="description",
            name="field",
            field=models.CharField(max_length=50, verbose_name="Tip opisa"),
        ),
        migrations.AlterField(
            model_name="description",
            name="initiative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="Naslov opisa"),
        ),
        migrations.AlterField(
            model_name="descriptiondefinition",
            name="field",
            field=models.CharField(max_length=50, verbose_name="Ime polja"),
        ),
        migrations.AlterField(
            model_name="descriptiondefinition",
            name="type",
            field=models.CharField(
                choices=[
                    ("MM", "MOTI ME!"),
                    ("II", "IMAM IDEJO!"),
                    ("ZM", "ZANIMA ME!"),
                ],
                default="MM",
                max_length=2,
                verbose_name="Tip pobude",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="odgovor"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=1, verbose_name="Vstni red"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(verbose_name="vprašanje"),
        ),
        migrations.AlterField(
            model_name="file",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Prikazno ime"),
        ),
        migrations.AlterField(
            model_name="file",
            name="status_initiative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="initiatives.statusinitiative",
                verbose_name="Status pobude",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Prikazno ime"
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Naslov pobude"
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiatives",
                to="initiatives.area",
                verbose_name="Področje",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiative_before",
                to="initiatives.image",
                verbose_name="Naslovna slika prej",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="cover_image_after",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiative_after",
                to="initiatives.image",
                verbose_name="Naslovna slika potem",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="V pregledu"),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="reviewer",
            field=models.CharField(
                choices=[
                    ("SA", "SUPER ADMIN"),
                    ("AA", "ADMIN PODROČNI"),
                    ("AP", "OCENJEVALEC PODROČNI"),
                    ("CA", "IZVAJALEC PODROČNI"),
                ],
                default="AA",
                max_length=2,
                verbose_name="Reviewer role",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="statuses",
            field=models.ManyToManyField(
                through="initiatives.StatusInitiative",
                to="initiatives.Status",
                verbose_name="Status pobude",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="type",
            field=models.CharField(
                choices=[
                    ("MM", "MOTI ME!"),
                    ("II", "IMAM IDEJO!"),
                    ("ZM", "ZANIMA ME!"),
                ],
                default="MM",
                max_length=2,
                verbose_name="Tip pobude",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiatives",
                to="initiatives.zone",
                verbose_name="Območje pobude",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="for_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="initiatives.area",
                verbose_name="Področje",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="initiative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Je email poslan?"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("nw", "NEW"), ("up", "UPDATED")],
                default="nw",
                max_length=2,
                verbose_name="Tip obvestila",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="number_of_members",
            field=models.IntegerField(verbose_name="Število članov"),
        ),
        migrations.AlterField(
            model_name="rejection",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Ime zavrnitve"),
        ),
        migrations.AlterField(
            model_name="rejection",
            name="note",
            field=models.TextField(verbose_name="Opis zavrnitve"),
        ),
        migrations.AlterField(
            model_name="restorepassword",
            name="key",
            field=models.CharField(max_length=50, verbose_name="ključ"),
        ),
        migrations.AlterField(
            model_name="status",
            name="default_email",
            field=models.TextField(verbose_name="Privzet email odgovor"),
        ),
        migrations.AlterField(
            model_name="status",
            name="note",
            field=models.TextField(verbose_name="Privzet opis statusa"),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="competent_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiative_statuses",
                to="initiatives.competentservice",
                verbose_name="Pristojna služba",
            ),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="email_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vsebina email odgovora"
            ),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="initiative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiative_statuses",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="is_email_sent",
            field=models.BooleanField(default=False, verbose_name="Je email poslan?"),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Opis statusa"),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="reason_for_rejection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="initiatives.rejection",
                verbose_name="Zavrnitev",
            ),
        ),
        migrations.AlterField(
            model_name="statusinitiative",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiative_statuses",
                to="initiatives.status",
                verbose_name="Status pobude",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="area",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="initiatives.Area",
                verbose_name="Področje",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="competent_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="initiatives.CompetentService",
                verbose_name="Pristojna služba",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="note",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Opis"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="initiatives.Organization",
                verbose_name="Organizacija",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SA", "SUPER ADMIN"),
                    ("AA", "ADMIN PODROČNI"),
                    ("AP", "OCENJEVALEC PODROČNI"),
                    ("CA", "IZVAJALEC PODROČNI"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Vloga",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Zahtevan podatek, manj kot 30 zanekov, črke, številke in samo @/./+/-/_.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w.@+ -]+$", "Vnesite ustrezno uporabniško ime.", "invalid"
                    )
                ],
                verbose_name="uporabniško ime",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="initiative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="initiatives.initiative",
                verbose_name="Pobuda",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Ime območja"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                srid=4326, verbose_name="Meje območja"
            ),
        ),
    ]
