# Generated by Django 3.1.5 on 2021-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0031_auto_20210719_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'All admin',
                'verbose_name_plural': 'All admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiatives.user',),
        ),
        migrations.AlterModelOptions(
            name='areaadminuser',
            options={'verbose_name': 'Nivo2 admini področni', 'verbose_name_plural': 'Nivo2 admini področni'},
        ),
        migrations.AlterModelOptions(
            name='areaappraiseruser',
            options={'verbose_name': 'Nivo3 skrbnik področni', 'verbose_name_plural': 'Nivo3 skrbniki področni'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativeappraiser',
            options={'verbose_name': 'Pobuda moti me (Nivo3 skrbnik področni)', 'verbose_name_plural': 'Pobude moti me (Nivo3 skrbnik področni)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativearea',
            options={'verbose_name': 'Pobuda moti me (Nivo2 admin področni)', 'verbose_name_plural': 'Pobude moti me (Nivo2 admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativecontractor',
            options={'verbose_name': 'Pobuda moti me (Nivo4 skrbnik - izvajalec)', 'verbose_name_plural': 'Pobude moti me (Novo4 cenilci izvajalci)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativesuper',
            options={'verbose_name': 'Pobuda moti me (Nivo1 superadmin)', 'verbose_name_plural': 'Pobude moti me (Nivo1 superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='contractorappraiseruser',
            options={'verbose_name': 'Nivo4 skrbnik - izvajalec', 'verbose_name_plural': 'Nivo4 skrbniki - izvajaleci'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativeappraiser',
            options={'verbose_name': 'Pobuda imam idejo (Nivo3 skrbnik področni)', 'verbose_name_plural': 'Pobude imam idejo (Nivo3 skrbnik področni)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativearea',
            options={'verbose_name': 'Pobuda imam idejo (Nivo2 admin področni)', 'verbose_name_plural': 'Pobude imam idejo (Nivo2 admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativecontractor',
            options={'verbose_name': 'Pobuda imam idejo (Nivo4 skrbnik - izvajalec)', 'verbose_name_plural': 'Pobude imam idejo (Nivo4 skrbnik - izvajalec)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativesuper',
            options={'verbose_name': 'Pobuda imam idejo (Nivo1 superadmin)', 'verbose_name_plural': 'Pobude imam idejo (Nivo1 superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativeappraiser',
            options={'verbose_name': 'Pobuda zanima me (Nivo3 skrbnik področni)', 'verbose_name_plural': 'Pobude zanima me (Nivo3 skrbnik področni)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativearea',
            options={'verbose_name': 'Pobuda zanima me (Nivo2 admin področni)', 'verbose_name_plural': 'Pobude zanima me (Nivo2 admin področni)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativesuper',
            options={'verbose_name': 'Pobuda zanima me (superadmin)', 'verbose_name_plural': 'Pobude zanima me (Nivo1 superadmin)'},
        ),
        migrations.AlterModelOptions(
            name='superadminuser',
            options={'verbose_name': 'Nivo1 Superadmin', 'verbose_name_plural': 'Nivo1 Superadmin'},
        ),
        migrations.AlterField(
            model_name='address',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='area',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PU', 'OBJAVLENO'), ('D', 'IZBRISANO')], default='PU', max_length=2, verbose_name='Status komentarja'),
        ),
        migrations.AlterField(
            model_name='competentservice',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='confirmemail',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='description',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='descriptiondefinition',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='descriptiondefinition',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalarea',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='status',
            field=models.CharField(choices=[('PU', 'OBJAVLENO'), ('D', 'IZBRISANO')], default='PU', max_length=2, verbose_name='Status komentarja'),
        ),
        migrations.AlterField(
            model_name='historicalcompetentservice',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicaldescription',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicaldescriptiondefinition',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicaldescriptiondefinition',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='historicalfaq',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='is_social_inovative_idea',
            field=models.BooleanField(default=False, verbose_name='Družbeno inovativna ideja'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='historicalrejection',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalstatusinitiative',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalstatusinitiative',
            name='publication_status',
            field=models.CharField(choices=[('d', 'Osnutek'), ('p', 'Objavljeno')], default='d', max_length=1, verbose_name='Publication Status'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email naslov'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalzone',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='image',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='is_social_inovative_idea',
            field=models.BooleanField(default=False, verbose_name='Družbeno inovativna ideja'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nw', 'NOVO'), ('up', 'OSEVŽENO')], default='nw', max_length=2, verbose_name='Tip obvestila'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='rejection',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='restorepassword',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='status',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='statusinitiative',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='statusinitiative',
            name='publication_status',
            field=models.CharField(choices=[('d', 'Osnutek'), ('p', 'Objavljeno')], default='d', max_length=1, verbose_name='Publication Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email naslov'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Urejano'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='initiatives.alladminuser', verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed', to='initiatives.alladminuser', verbose_name='Reviewer'),
        ),
    ]
