# Generated by Django 3.1.5 on 2022-03-08 12:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0033_auto_20220128_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Naslov', 'verbose_name_plural': 'Naslovi'},
        ),
        migrations.AlterModelOptions(
            name='alladminuser',
            options={'verbose_name': 'Vsi admini', 'verbose_name_plural': 'Vsi admini'},
        ),
        migrations.AlterModelOptions(
            name='areaadminuser',
            options={'verbose_name': 'Vodja področja - nivo 2', 'verbose_name_plural': 'Vodje področij - nivo 2'},
        ),
        migrations.AlterModelOptions(
            name='areaappraiseruser',
            options={'verbose_name': 'Skrbnik področja - nivo 3', 'verbose_name_plural': 'Skrbniki področij - nivo 3'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativeappraiser',
            options={'verbose_name': 'Pobuda moti me (Skrbnik področja - nivo 3)', 'verbose_name_plural': 'Pobude moti me (Skrbnik področja - nivo 3)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativearea',
            options={'verbose_name': 'Pobuda moti me (Vodja področja - nivo 2)', 'verbose_name_plural': 'Pobude moti me (Vodja področja - nivo 2)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativecontractor',
            options={'verbose_name': 'Pobuda moti me (Izvajalec - nivo 4)', 'verbose_name_plural': 'Pobude moti me (Izvajalci - nivo 4)'},
        ),
        migrations.AlterModelOptions(
            name='bothersinitiativesuper',
            options={'verbose_name': 'Pobuda moti me (Superadmin - nivo 1)', 'verbose_name_plural': 'Pobude moti me (Superadmin - nivo 1)'},
        ),
        migrations.AlterModelOptions(
            name='contractorappraiseruser',
            options={'verbose_name': 'Izvajalec - nivo 4', 'verbose_name_plural': 'Izvajaleci - nivo 4'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativeappraiser',
            options={'verbose_name': 'Pobuda imam idejo (Skrbnik področja - nivo 3)', 'verbose_name_plural': 'Pobude imam idejo (Skrbnik področja - nivo 3)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativearea',
            options={'verbose_name': 'Pobuda imam idejo (Vodja področja - nivo 2)', 'verbose_name_plural': 'Pobude imam idejo (Vodja področja - nivo 2)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativecontractor',
            options={'verbose_name': 'Pobuda imam idejo (Izvajalec - nivo 4)', 'verbose_name_plural': 'Pobude imam idejo (Izvajalec - nivo 4)'},
        ),
        migrations.AlterModelOptions(
            name='ideainitiativesuper',
            options={'verbose_name': 'Pobuda imam idejo (Superadmin - nivo 1)', 'verbose_name_plural': 'Pobude imam idejo (Superadmin - nivo 1)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativeappraiser',
            options={'verbose_name': 'Pobuda zanima me (Skrbnik področja - nivo 3)', 'verbose_name_plural': 'Pobude zanima me (Skrbnik področja - nivo 3)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativearea',
            options={'verbose_name': 'Pobuda zanima me (Vodja področja - nivo 2)', 'verbose_name_plural': 'Pobude zanima me (Vodja področja - nivo 2)'},
        ),
        migrations.AlterModelOptions(
            name='interestedinitiativesuper',
            options={'verbose_name': 'Pobude zanima me (Superadmin - nivo 1)', 'verbose_name_plural': 'Pobude zanima me (Superadmin - nivo 1)'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Obvestila', 'verbose_name_plural': 'Obvestila'},
        ),
        migrations.AddField(
            model_name='historicalstatusinitiative',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Avtor'),
        ),
        migrations.AddField(
            model_name='statusinitiative',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives_statusinitiative_author', to='initiatives.user', verbose_name='Avtor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='archived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arhivirano'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Lokacija'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='reviewer',
            field=models.CharField(choices=[('SA', 'SUPER ADMIN'), ('AA', 'ADMIN PODROČNI'), ('AP', 'OCENJEVALEC PODROČNI'), ('CA', 'IZVAJALEC PODROČNI')], default='AA', max_length=2, verbose_name='Vloga Skrbnika/izvajaleca'),
        ),
        migrations.AlterField(
            model_name='historicalinitiative',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='initiatives.alladminuser', verbose_name='Skrbnik/Izvajalec'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='archived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arhivirano'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Lokacija'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_initiatives', to=settings.AUTH_USER_MODEL, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='reviewer',
            field=models.CharField(choices=[('SA', 'SUPER ADMIN'), ('AA', 'ADMIN PODROČNI'), ('AP', 'OCENJEVALEC PODROČNI'), ('CA', 'IZVAJALEC PODROČNI')], default='AA', max_length=2, verbose_name='Vloga Skrbnika/izvajaleca'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed', to='initiatives.alladminuser', verbose_name='Skrbnik/Izvajalec'),
        ),
        migrations.AlterField(
            model_name='reviewerhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_history', to='initiatives.alladminuser', verbose_name='Skrbnik/Izvajalec'),
        ),
    ]
