# Generated by Django 3.1.5 on 2021-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('MM', 'MOTI ME!'), ('II', 'IMAM IDEJO!'), ('ZM', 'ZANIMA ME!')], default='MM', max_length=2, verbose_name='Initiative type')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False, verbose_name='In review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
