# Generated by Django 3.1.5 on 2021-02-18 16:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.db import models as geo_models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Address of initiative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='initiatives.area', verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_initiative_author', to='initiatives.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_before', to='initiatives.image', verbose_name='Cover image before'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='cover_image_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_after', to='initiatives.image', verbose_name='Cover image after'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_initiatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='statuses',
            field=models.ManyToManyField(through='initiatives.StatusInitiative', to='initiatives.Status', verbose_name='Status of initiative'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='initiatives.zone', verbose_name='GEO Zone of initiative'),
            preserve_default=False,
        ),
    ]
