# Generated by Django 3.1.5 on 2021-02-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_initiative_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BothersInitiative',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiative.initiative',),
        ),
        migrations.CreateModel(
            name='IdeaInitiative',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiative.initiative',),
        ),
        migrations.CreateModel(
            name='InterestedInitiative',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('initiative.initiative',),
        ),
    ]
