apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izboljsajmo-maribor-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "6m"
    nginx.org/client-max-body-size: "6m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.izboljsajmo-maribor.lb.djnd.si
    # REMOVED DURING SHUTDOWN
    # - api.izboljsajmo.maribor.si
    secretName: izboljsajmo-maribor-backend-tls
  rules:
  - host: api.izboljsajmo-maribor.lb.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: izboljsajmo-maribor-backend
            port:
              number: 80
  # REMOVED DURING SHUTDOWN
  # - host: api.izboljsajmo.maribor.si
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: izboljsajmo-maribor-backend
  #           port:
  #             number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izboljsajmo-maribor-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - files.izboljsajmo-maribor.lb.djnd.si
    # REMOVED DURING SHUTDOWN
    # - files.izboljsajmo.maribor.si
    secretName: izboljsajmo-maribor-nginx-tls
  rules:
  - host: files.izboljsajmo-maribor.lb.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: izboljsajmo-maribor-nginx
            port:
              number: 80
  # REMOVED DURING SHUTDOWN
  # - host: files.izboljsajmo.maribor.si
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: izboljsajmo-maribor-nginx
  #           port:
  #             number: 80
