name: Publish Docker image
on:
  push:
    branches:
      - 'k8s'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Docker meta to create tag
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            rg.fr-par.scw.cloud/djnd/izboljsajmo-maribor-backend
          # add git short SHA as Docker tag
          tag-custom:
            - ${{ env.GITHUB_SHA }}
          tag-custom-only: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}
      -
        name: Build and push BACKEND
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Build and push FRONTEND
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Update frontend image version in kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ env.GITHUB_SHA }}'/" kustomize/kustomization.yaml
      -
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '.'
          author_name: GitHub action

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update image versions in kustomize/kustomization.yaml'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          # 'NO-PULL or --no-rebase or --no-ff or --rebase'
          pull_strategy: 'NO-PULL'
